/**
 * ClientDeliverables — Simplified deliverables view for client mode.
 *
 * Shows outputs and files without internal metadata.
 * Operator mode falls through to the existing DeliverablesView.
 */

import type { CSSProperties } from "react";
import { usePolling } from "../hooks/use-polling";
import { fetchDeliverables } from "../lib/queries";
import type { Deliverable } from "../lib/types";
import { PageHeader, Spinner, ErrorBanner, StatusBadge, DataTable } from "./shared";
import type { Column } from "./shared";

export function ClientDeliverables() {
  const { data: deliverables, loading, error } = usePolling<Deliverable[]>({
    fetcher: fetchDeliverables,
    interval: 15_000,
  });

  if (loading && !deliverables) return <Spinner />;

  const columns: Column<Deliverable>[] = [
    { key: "filename", header: "File", render: (d) => d.filename, width: "30%" },
    { key: "type", header: "Type", render: (d) => d.content_type },
    {
      key: "size",
      header: "Size",
      render: (d) => d.size_bytes ? `${(d.size_bytes / 1024).toFixed(1)} KB` : "—",
    },
    { key: "status", header: "Status", render: (d) => <StatusBadge value={d.status} /> },
    {
      key: "date",
      header: "Date",
      render: (d) => new Date(d.created_at).toLocaleDateString(),
    },
  ];

  return (
    <div>
      <PageHeader title="Outputs" subtitle="Files and reports generated by your tasks" />
      {error && <ErrorBanner message={error} />}

      {(deliverables ?? []).length === 0 ? (
        <div style={emptyStyle}>No outputs yet. Outputs will appear here once tasks complete.</div>
      ) : (
        <DataTable
          columns={columns}
          rows={deliverables ?? []}
          rowKey={(d) => d.id}
        />
      )}
    </div>
  );
}

const emptyStyle: CSSProperties = {
  textAlign: "center",
  padding: 48,
  color: "#64748b",
  fontSize: 14,
};

export default ClientDeliverables;
